---
abstract: 'Returns Moo Modifiers as a Hash'
author:
  - 'Robert Acock <thisusedtobeanemail@gmail.com>'
build_requires:
  Exporter: '0'
  Moo: '1.001001'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-ReturnModifiers
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '0'
  perl: '5.006'
version: '0.09'
